### ISSUE TITLE
When an eip is bound to a NIC, a tag is automatically added

### ISSUE THREAD

**Issue by Dup4** [volcengine/terraform-provider-volcengine#76]
```hcl
resource "volcengine_eip_address" "ecs_bytesbc_boe_test_external_ip" {
  name = "ecs-bytesbc-boe-test-external-ip"

  billing_type = "PostPaidByTraffic"
  bandwidth    = 200
  isp          = "BGP"

  project_name = var.volc_project_name
}

resource "volcengine_eip_associate" "ecs_bytesbc_boe_test" {
  allocation_id = volcengine_eip_address.ecs_bytesbc_boe_test_external_ip.id
  instance_id   = volcengine_ecs_instance.ecs_bytesbc_boe_test.id
  instance_type = "EcsInstance"
}
```

<img width="903" alt="image" src="https://user-images.githubusercontent.com/38343778/228401524-96b941f0-7681-4a01-bb76-f91f7272d2f3.png">

When I `terraform apply` an eip and its binding, then again `terraform plan` prompts a difference in state with the remote end.

**Comment by zpp12354321** [comment]
please update to version v0.0.64, we have fixed this issue @Dup4

**Comment by Dup4** [comment]
> please update to version v0.0.64, we have fixed this issue @Dup4

When I upgrade to v0.0.64 from v0.0.51, it will need to recreate ecs.

<img width="895" alt="image" src="https://user-images.githubusercontent.com/38343778/228849640-2c8fff89-432e-45dd-a5d1-8629b41269e5.png">
