### ISSUE TITLE
fix the "encrypted" to "encoded" from the description of "volcengine_vke_node_pool"

### ISSUE THREAD

**Issue by kongweiguo** [volcengine/terraform-provider-volcengine#80]
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/1670845/229330888-5e7972cd-ce34-4a1f-b9db-c6e7adac8fe7.png">

**Comment by zpp12354321** [comment]
Hi，Thanks for submitting this issue. We will fix this issue in the next version.

**Comment by xuyaming0800** [comment]
fixed at v0.0.66
